### ISSUE TITLE
Hibernate naming convention

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#100]
make sure we can setup so it names columns with camelCase. It changed in hibernate 5.

also figure out how to set it up so we don't need to specify this stuff in out domain mappings
```
calc column: 'calcId'
flex column: 'flexId'
info column: 'infoId'
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/681349105892800/681357375019174)

**Comment by alexeyzvegintcev** [comment]
@basejump to setup columns in camelCase we can just use 
 ```naming_strategy: org.hibernate.cfg.EJB3NamingStrategy```
in hebirnate section it is predefined NamingStrategy that resolves all issues except one - associations  are still uses underline.
the best way that we can go to have column: 'calcId' is to use approach related to auditTrail to add `column` property dynamically, but not sure it worst it
 what do you think?

**Comment by basejump** [comment]
see https://stackoverflow.com/questions/32165694/spring-hibernate-5-naming-strategy-configuration#32166571
https://stackoverflow.com/questions/32437202/improvednamingstrategy-no-longer-working-in-hibernate-5

It looks like the naming strategy by default does not add the `_`? so custNum will be custNum in the db?
We just need to verify `Cutsomer customer` -> customerId and not customer_id so we don't need to specify it. I don't think using AST annotations is the right way as we need to hook into the table creation.

**Comment by alexeyzvegintcev** [comment]
https://github.com/grails/gorm-hibernate5/issues/67

https://github.com/grails/gorm-hibernate5/issues/66

**Comment by basejump** [comment]
https://github.com/grails/gorm-hibernate5/pull/69
