### ISSUE TITLE
EntityMapBinder: whiteList and blackList

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#103]
need to be able to pass these in. 

should also lean on the field added to the domain entities by default `$defaultDatabindingWhiteList`
DefaultASTDatabindingHelper.DEFAULT_DATABINDING_WHITELIST and its use can be seen in Grails source getBindingIncludeList in DataBindingUtils along with how it caches it in CLASS_TO_BINDING_INCLUDE_LIST.

**Comment by basejump** [comment]
@snimavat lets try a different route hear so we dont recreate the wheel. let extend the simpleDatabbinder from grails and override. see if we casn get the same performace

**Comment by snimavat** [comment]
Yeah, was thinking the same... i would personally prefer to do that. will do it
