### ISSUE TITLE
Date, LocalDate, LocalDateTime testing and defaults

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#117]
see http://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/
https://hibernate.atlassian.net/browse/HHH-11396
https://vladmihalcea.com/2017/03/14/how-to-store-date-time-and-timestamps-in-utc-time-zone-with-jdbc-and-hibernate/
and
https://stackoverflow.com/questions/31965179/whats-new-in-hibernate-orm-5

we need some integration tests to see and make sure the values getting stored in the DB are agnostic of timezone. 

Also add good docs on how it works and how to setup the app and what the timezone impact has if any. Also doc any special setups that should be done on the DB and server for time date and zones as well as if its needed to tell the app server what time zone is on db server. 
I think that if we recommend and then we use UTC everywhere we are better off but if clients wont do it on their servers then we need to have a very clear understanding and setup for it.

**Comment by snimavat** [comment]
@basejump we can use the ```hibernate.jdbc.time_zone``` which stores and retrives date in specified timezone. And we can configure it to be UTC. That would save us from forcing default timezone of system or JVM. We can configure it to be what timezone client prefers to have their app on.
However dates on ui will be displayed on that timezone (UTC)

Other option could be, dates are stored as UTC. And we can have user specific setting for his timezone. In that case we will need to convert dates to and from utc to users timezone before dates are displayed or before dates are stored. This would be more work but user will see dates in his own time.

**Comment by snimavat** [comment]
Should we set timezone to UTC for integration tests ?

**Comment by basejump** [comment]
still need some docs on this with references to the links above if they are relevant
