### ISSUE TITLE
Figure out what the slow unit tests are and why. 

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#118]
![2017-12-28_14-42-08](https://user-images.githubusercontent.com/187726/34422903-379166ea-ebde-11e7-9177-0da80604a70c.gif)

 test 146-152? are very slow, what are they?

**Comment by NickPavlov** [comment]
@basejump  these tests are using Grails async event listener to check repo events and they have delays  inside - https://github.com/yakworks/gorm-tools/blob/master/plugin/src/test/groovy/gorm/tools/repository/RepositoryEventPublisherSpec.groovy#L73. Should we keep them or do something to speed up them?

**Comment by basejump** [comment]
do we really need to have delays? especially for 1 second?
