### ISSUE TITLE
DomainAutoTest questions and docs

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#129]
- [x] Does it need to extend GormToolsHibernateSpec?

The tests should test domain and Repo functionality, so may require hibernate testing features.

- [x] break out the logic to "BuildExampleData" so we can more easily get a map and it can be used in any test. This is what I meant by leaning on the build-test-data. Could use some ideas or code form there.  see refs below
- [x] I'm not seeing any docs for this. do they exist?
- [x] explain how to override methods in a test for special handling. 
- [x] finish the docs for repository/inro.md `### Testing the ProjectRepo Changes`
// Added docs how I see it not sure that you think exactly about such docs
 
https://github.com/longwa/build-test-data/blob/master/build-test-data/src/main/groovy/grails/buildtestdata/DomainInstanceBuilder.groovy
https://github.com/longwa/build-test-data/blob/master/build-test-data/src/main/groovy/grails/buildtestdata/TestDataBuilder.groovy

**Comment by alexeyzvegintcev** [comment]
@basejump   added some comments for your questions and pushed my changes to https://github.com/yakworks/gorm-tools/compare/129-DomainTest-refactoring  not finished yet - plan to work on it a bit more, so didnt make a PR
