### ISSUE TITLE
BeanPathTool enhancement

### ISSUE THREAD

**Issue by alexeyzvegintcev** [yakworks/gorm-tools#150]
It should be able to return "includes" so "foo.*" -> ["foo.name", "foo.num", ...]
related to https://github.com/yakworks/gorm-rest-api/issues/7

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/681349105892800/681357379456307)

**Comment by basejump** [comment]
good. Lets get this working in Jsonify. the Jsonify render method can intercept the includes and transalate it before before passing it through to the `getViewHelper().render`
