### ISSUE TITLE
GormUtils.copyDomain() doesn't copy composite identifier fields

### ISSUE THREAD

**Issue by NickPavlov** [yakworks/gorm-tools#152]
In Grails 3.3.2 PersistentEntity.persistentProperties doesn't return fields that are composite identifiers. Since GormUtils.copyDomain() is based on persistentProperties it might break some existing logic which uses copyDomain().

For example, copyDomain() for ActivityLink doesn't copy linkedId and linkedEntity fields as it was before.

Possible solutions:
1) We can modify copyDomain to be able to copy composite fields by default and provide an ability to disable it (e.g. using "ignoreComposite" parameter, like it is done for associations)
2) We can modify "copyDomain" to copy composite fields by default and in case we need to disable copying of these fields, we can use override map (which is already implemented in copyDomain) and provide them in it with null values.
3) Another possible solution is to leave copyDomain as it is (without copying 
 composite fields) and in case we need to copy such fields, just add them to the "override" parameter map, thus composite fields will be copied as well. 
Currently, this solution is used in ActivityRepo.copy() to copy ActivityLink entities.
4) We can implement our own version of getPersistentProperties method in GormMetaUtils that will return persistent properties and composite identifiers for the given domain class, but without id field. And use this method in copyDomain, to restore it's previous behavior.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/681349105892800/681357157307330)

**Comment by snimavat** [comment]
I think, ids are unique, should not be copied by default, if one of the field in composite id has to be copied, it should be passed in overrride.
