### ISSUE TITLE
Helper-traits for integration tests-Docs

### ISSUE THREAD

**Issue by NickPavlov** [yakworks/gorm-tools#160]
The support for helper-traits for integration tests should be added. Those helpers should be composable with the other helpers from the client app/plugin that use gorm-tools. The client app/plugin should be able to define its own similar helper traits with its own specific logic. If gorm-tools is used by a plugin, then all client plugin-specific helper traits should not depend on test dependencies (like JUnit). Thus, the helpers from gorm-tools should provide them a way to do so. The goal is to make the client plugin-specific helpers reusable in tests of the app that includes a plugin that includes gorm-tools.

- [x] traits
- [ ] docs
- [x] tests

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/681349105892800/681357145657840)

**Comment by snimavat** [comment]
@basejump i think we have stable test traits for gorm-tools now tht we use in all other projects. we can probably close this task
