### ISSUE TITLE
fillInStackTrace for the exceptions when they get hrown

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#17]
https://stackoverflow.com/questions/36343209/which-part-of-throwing-an-exception-is-expensive

https://stackoverflow.com/questions/22170984/how-do-i-make-grails-get-to-throw-exception-on-record-not-found

https://github.com/grails-plugins/grails-spring-security-core/blob/master/src/main/groovy/grails/plugin/springsecurity/userdetails/NoStackUsernameNotFoundException.groovy

http://normanmaurer.me/blog/2013/11/09/The-hidden-performance-costs-of-instantiating-Throwables/

http://java-performance.info/throwing-an-exception-in-java-is-very-slow/

**Comment by jdabal** [comment]
@snimavat  still open?

**Comment by snimavat** [comment]
@basejump lets discuss when you are around.
