### ISSUE TITLE
EntityMapBinder issue with CLASS_TO_BINDING_INCLUDE_LIST

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#181]
EntityMapBinder has method getBindingIncludeList which caches the whitelist fields in CLASS_TO_BINDING_INCLUDE_LIST.

CLASS_TO_BINDING_INCLUDE_LIST is defined in super class GrailsWebDataBinder. 
GrailsWebDataBinder also defines getBindingIncludeList. however the way fields are looked up is different in EntityMapBinder and GrailsWebDataBinder. EntityMapBinder uses persistent properties, where as GrailsWebDataBinder uses all declared fields.

So if a domain has been earlier been bound using GrailsWebDataBinder, binding the same domain with
EntityMapBinder will result in errors, because the whitelist field will contain fields which are not persistent properties. 

@basejump

**Comment by snimavat** [comment]
@basejump

**Comment by basejump** [comment]
not sure I follow where this is an issue

**Comment by basejump** [comment]
can you create a test here in gorm-tools to show the issue you are running into? Whats the solution to this? I still think we should refactor how its done in Grails and submit a PR. Its currently pretty messed up and why its so much faster for ours.

**Comment by snimavat** [comment]
@basejump See above commit which has failing test

**Comment by snimavat** [comment]
@basejump I have fixed the issue for now, using a seperate CLASS_TO_BINDING_INCLUDE_LIST for EntityMapBinder, so it is not shared with GrailsWebDataBinder. Anyway it should not be shared as both of them works differently and has different fields cached in CLASS_TO_BINDING_INCLUDE_LIST.

**Comment by snimavat** [comment]
@basejump can we merge this PR - nothing noticable in benchmarks. GrailsWebDataBinder isnt supposed to be used in our project anyway.. so this change makes no difference.
