### ISSUE TITLE
insertAndSave name change

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#20]
why did we name it this? what was wrong with insert?
can we call it create? don't like the name.

**Comment by jdabal** [comment]
@snimavat  is it still open ?

**Comment by snimavat** [comment]
@jdabal @basejump I dont see insertAndSave -- the doInsert etc methods are aready documented #26

**Comment by basejump** [comment]
you don't see insertAndSave? did you do a search?

**Comment by snimavat** [comment]
I was looking in wrong branch, I see that the name has to be changed because of a other method with same name (insert (Map m) but different return type being added to domains by grails AST -- which results in compilation errors
