### ISSUE TITLE
@Value does not work during unit tests

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#205]
@Value annotation does not work during unit tests.

The value annotation is handeled by AutowiredAnnotationBeanPostProcessor 
Which is even though registered in test context, it some how does not seem to work.
This is issue with grails

Look at 
GrailsApplicationBuilder
AnnotationConfigUtils.registerAnnotationConfigProcessors((BeanDefinitionRegistry)beanFactory) registeres the post processor

**Comment by basejump** [comment]
works now
