### ISSUE TITLE
year and month function support

### ISSUE THREAD

**Issue by ibmsoft** [yakworks/gorm-tools#219]
we can use following query
Person.where{
  year(dateCreated) == 2019 && month(dateCreated) = 12
}

how to do in gorm--tools

**Comment by snimavat** [comment]
Under the hood, where queries uses DetachedCriteria

Person.query{} returns a detached criteria, upon which u can build further, should work.

```
def query = Person.query([:])
//add more restrictions
query - query.build {
   year(xx)
}
```

Or, pass closure as 2nd argument

```
  Person.query([x:x]) {
            year(xx)
        }
```
