### ISSUE TITLE
add Tags to Contact

### ISSUE THREAD

**Issue by jdabal** [yakworks/gorm-tools#325]
User story:
As a user I want to tag Contact to receive different emails or communication types. My tags could be "receive statement", "receive invoices", "receive dunning letters minor only", "receive dunning letters critical", "call for credit limit", etc. Each contact can have one or many tags. Later on we can do logic based on tags assigned to contacts.

look how we are using Tags for Activity/Org/ArTran and do the same for Contact.

**Comment by ken-roberts** [comment]
Reworking Contact code per screen share with Josh.
1. Add specs for Orgs and Contact per copied ActivitySpec. 
2. Code to make tests pass.
