### ISSUE TITLE
test bulk create

### ISSUE THREAD

**Issue by jdabal** [yakworks/gorm-tools#348]
There is no test that is calling restRepositoryApi.bulkCreate. I started one in OrgRestAPiSpec.testing bulk create but it's not working for me. Can you complete?

Also, is OrgRestAPiSpec.testing bulkUpdate doing the right thing ? 

I moved all columns from Job to JobTrait so BulkRestApiSpec is working. Can we add tests for Job values there?

**Comment by snimavat** [comment]
Bulkupdate in bulkable is not desiged/implemented yet -- so no tests for now.
