### ISSUE TITLE
Return promise from bulkable operations + implement errorThreshold, async and sliceSize at the same time

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#356]
pass in errorThreshold, async and sliceSize to BulkableArgs

-  **async** is passed as bulkable args - bulkable operation should return with a promise which would either resolve with bulk result or fail

- **sliceSize**
Add to BulkableArgs:
/**
     * the size of the lists when collated or sliced into chunks,
     * overrides defaults that get set from jdbc.batch_size
     */
    Integer sliceSize

- **errorThreshold**
- 
pass in async value to BulkableArgs:

![image](https://user-images.githubusercontent.com/421237/136057550-40e7d8c6-de09-4e9f-9d2c-3e2d6ee02227.png)

**Comment by jdabal** [comment]
we decided to do async.
