### ISSUE TITLE
StackoverflowError during compile when implementing GormRepoEntity

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#383]
In some very special case, implementing GormRepoEntity results in Stackoverflow error. 
This could be related to some AST, or a likely groovy compiler bug 

Groovy compiler had few such StackoverFlowError issues related to generics [here](https://issues.apache.org/jira/browse/GROOVY-7722)  and [here](https://issues.apache.org/jira/browse/GROOVY-7742) 

In domain9, this error comes up with ArAdjustLine, when `ArAdjustLine implements GormRepo<AradjustLine, AradjustLineRepo`

@basejump

**Comment by snimavat** [comment]
Happens with many more domains for example, GlJournal, ArTranJournal etc

**Comment by basejump** [comment]
yes, its still and issue with groovy 3 too. the solution is to not use GormRepoEntity and use RepoEntity when it happens and manually implement the getRepo when needed.
