### ISSUE TITLE
external-config is loading config twice

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#387]
Joshua:rocket:  8:30 PM
and ran in circles for a bit diagnosing a problem we had yesterday. Need to create an issue. the new 2.0.1 version of external-config is loading things twice.

snimavat  8:31 PM
ok

Joshua:rocket:  8:33 PM
actually, can you create issue in gorm-tools and see if you can reproduce it there, in resitfy maybe. not high priority right now but take a look. super easy to reproduce in domain9, just bump to his new lib 2.0.1 its dk.sbglas.. now. and when you run rcm-api youll see it trying to do datasource-config tiwce,

**Comment by basejump** [comment]
solved, forked the external config in spring-kit project.and dont use the one that relays on micronaut, which was causing the duplication
