### ISSUE TITLE
have orgMember that is not required on all customers

### ISSUE THREAD

**Issue by jdabal** [yakworks/gorm-tools#418]
At RNDC some states will have factory and sales, but others worn't . Can we have setting on orgDimension that is not required? Or just don't validate factory and sales? For example:
- in California (CA is division) it has : custAccount.customer.branch.division 
- in Texas (TX is division) it has : custAccount.customer.branch.division and custAccount.factory and custAccount.sales
- in Florida (FL is division) it has : custAccount.branch.division and custAccount.customer.division

**Comment by basejump** [comment]
@jdabal this still needed?
