### ISSUE TITLE
Blank String is turned into null -- will be problem for updates

### ISSUE THREAD

**Issue by jdabal** [yakworks/gorm-tools#425]
all blank Strings will be null, so the problem will be with update when you want to null something out in update, for example 
update Contact phone number you cannot put blank because it will be turned to null and not used in update:

EntityMapBinder.processStringValue

**Comment by basejump** [comment]
@snimavat what happens when we try and null out a field using and update? is there already a mechanisim in place?

**Comment by basejump** [comment]
@jdabal @snimavat can you update this issue so we have somethign searchable with how this works? and can update our base API docs too. 

- what happens now to null out a field? 
- is currently functionality the way it should stay or is there something left to do here?
