### ISSUE TITLE
base gormDaoSupport redesign

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#43]
- [x] first update all Transactional annotations to be from gorm vs grails
- [x] add bindFast option as benchmarks show grails binding to be super slow
- [x] refactor to use interfaces and traits. grails-datastore-gorm as an example. GormEntityApi, and GormEntity provide examples.

**Comment by snimavat** [comment]
@basejump lets discuss this when u are available. i have few things to discuss.

**Comment by snimavat** [comment]
I think our current design is not exact but similar to GormEntityAPI.
The way grails-data-store-gorm does it, they have GormEntity trait which adds isntance level methods to domain, and forwards the calls to GormInstanceApi. Similarly we have DaoDomainTrait which adds instance level methods to domains (eg persist, update, remove) and forwards the calls to dao or GormDaosupport

**Comment by basejump** [comment]
these are some ideas to keep things consitent

- GormDao - trait for the daos. 
- DefaultGormDao - implementation that will be the bean that gets created when there isn't one. 
- GormDaoStaticApi - for the statics , in line with GormStaticApi.
- GormDaoInstanceApi - in line with  GormInstanceApi. 
- GormDaoEnhancer - in line with GormEnhancer. will have statics 
 like gormenhancer. GormDaoEnhancer.findInstanceApi and findStatic... which will accept the Class for the domain.

**Comment by snimavat** [comment]
@basejump , i see ur mock classes. I still dont think we need GormDaoEnhancer.

We dont need GormDaoStaticApi and GormDaoInstanceApi, in ourcase the api class is not going to be always same (eg GormStaticApi or GormInstanceApi). Its either a real dao created explicitly, or DefaultGormDao.

What we need is: 
- Rename DaoDomainTrait to DaoEntity and cleanup
- GormDao trait and rename GrormDaoSupport to DefaultGormDao and implement GormDaoTrait

I see u have done some of this in a branch. 
However u have empty GormDaoEnhancer whici i dont think we need.
You have some spring data gorm repositories, i dont knw whts plan here.
And ur GormDao trait is not 100% done i belive, so i guess it needs to be completed.

Do you have any specific reason for converting GormDaoSupport to a trait from an abstract class ?
Are we trying to achieve some thing here with some well known benifits ? Traits makes it very ugly when we have to call an overriden method on superclass, in our case the trait.

**Comment by snimavat** [comment]
@basejump please use 43-dao-redesign branch for further commits if u do any, its based on latest master and has your changes too from 43-new-GormDa0o.
