### ISSUE TITLE
Remove Spring proxies based transaction support

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#44]
Grails 3.3 has removed support for spring proxies based transactions, and supports just AST. Dao should remove the support for proxies too.

So
When registering beans, we dont check if we should create proxies or simple spring beans. should always be regular spring beans, as transaction stuff would have been weaved using AST

Look at services plugin for example.

@basejump

**Comment by basejump** [comment]
I think I did this already yesterday when I fixed the 2.5 to 3.x conversion issues with it creating a dao on very call to XXX.dao....

**Comment by snimavat** [comment]
Yes, closing it
