### ISSUE TITLE
FastDataBinder

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#46]
creating a gorm.tools.FastDataBinder in gorm-tools. Should be a bean that we can inject into the daos and use. We can move the bindFast out of a static in GormUtils, that static can still be there but it should redirect to FastDataBinder bean. See BenchmarkDatabindingService.setPropsFastIterate for more on what should be done to keep it fast but fall down to the converters if need be.  you guys can figure out who takes it. 
I leaned on the grails source for SimpleDataBinder to figure out how they are inject and getting the registered ValueConverters. They are slow as fuck which is why I do the 2 checks for the most common occurences, which would be numbers and dates. there is room to improve the DateUtil.parseJsonDate if we make those SimpleDate formats at the class level instead of creating them on every call.

The performance should match or be better than 4.5s setPropsFastIterate and within 1 second of the useStaticSettersInDomain- static setters benchmark. to keep it working I munged together but I think the static lookups on bean is slowing it way down to 13.1s. 

- setters or property copy on associations with 20 fields
3.517s useStaticSettersInDomain CityFat | 111690 rows
4.549s setPropsFastIterate CityFat | 111690 rows
13.118s daoCreateNewFast CityFat | 111690 rows
8.387s useDynamicSettersFat CityFat | 111690 rows

**Comment by snimavat** [comment]
Will take it

**Comment by snimavat** [comment]
>  DateUtil.parseJsonDate if we make those SimpleDate formats at the class level instead of creating them on every call.

@basejump Dateformats are not threadsafe, so probably cant be at class level for Dateutils

**Comment by snimavat** [comment]
Have a look https://github.com/yakworks/gorm-tools/commit/557e892d964be2173a339444fede9c1b6bf15af2

**Comment by basejump** [comment]
see #50 as well. should implement a trait or interface so we can inject and override the databinder property for a dao.

**Comment by basejump** [comment]
need to beef up and consolidate tests.

**Comment by basejump** [comment]
closing and adding a new issue
