### ISSUE TITLE
Document MultiFormatDateConverter, where its used and what its for

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#48]
https://github.com/yakworks/gorm-tools/blob/master/plugin/src/main/groovy/gorm/tools/beans/MultiFormatDateConverter.groovy

**Comment by alexeyzvegintcev** [comment]
@basejump Due to the fact that we have fastDatabinder that handles date strings convertation, we dont need MultiFormatDateConverter

**Comment by basejump** [comment]
what if we are not using fastDatabinder, which we may not in many cases where performance is not a problem
