### ISSUE TITLE
GormDao cleanup for list/query

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#49]
- [x] is the @Value working on the trait for criteriaKeyName? show a test where this is set in config and works
- [x] refactor to a MangoQuery bean with a MangoQueryApi trait so query, countTotals, buildCriteria logic are in that bean. there is to much logic in the GormDao trait.
- [x] a custom dao should be able to @Autowire its custom MangoQuery bean to use so we can implement and inject a variation if desired. 
- [x] criteriaKeyName can then be moved into the MangoQuery

**Comment by alexeyzvegintcev** [comment]
@basejump not sure do we realy need MangoQueryApi?
