### ISSUE TITLE
GormDao needs more tests

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#50]
- [x]  test the "event" methods
- [x] test that a new binder can be injected into a dao to replace the default fastbinder. I think we should be programming to an interface or trait in order to do this
- [ ]

**Comment by snimavat** [comment]
@basejump should we create a subclass of grails.databinding.DataBinder !?  Or you are planning to have our own interface for DataBinder

**Comment by basejump** [comment]
@snimavat , GormDaoSpec needs to be exercised more. Lots of gaps. Might be best to setup a DefaultGormDao and use that for testing it. Can do this at same time as exception refactoring

**Comment by NickPavlov** [comment]
@basejump the issue can be closed

**Comment by basejump** [comment]
@NickPavlov in your tests you check e.message.contains, those can change and might be removed. best to test the e.messageCode

**Comment by basejump** [comment]
Will add fixme's and setup a lunch and learn for patterns. closing this for now
