### ISSUE TITLE
External Groovy Scripts For Dao Events

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#51]
We want to be able to have external groovy scripts to run custom business logic during the dao events. For example, at one customer we do special customer.num generation before a new customer object is saved.  

this plugin should detect an external scripts executor plugin. 
we should have a contract on how the scripts are called. Either we have the script return an object implementing a trait or interface and then it can get registerd, or we have the script run and register a listener using the grails 3.3 events.

see the end of this as an example. https://github.com/Netflix/asgard/blob/master/grails-app/conf/spring/resources.groovy
we could setup reloadable groovy beans. 

see https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#groovy and http://mrhaki.blogspot.com/2013/03/grails-goodness-use-constructor.html

**Comment by snimavat** [comment]
We can do the similar thing as asgard example above, register groovy beans from scripts.
The beans can subscribe to events. Dao will need to fire events using grails event mechanism (We currently dont do that)

**Comment by snimavat** [comment]
Example in benchmarks project

**Comment by basejump** [comment]
Add instructions for how we are doing this for events to the docs.

**Comment by basejump** [comment]
Example doesn't look right. Good example for how to add listeners but not for refreshable beans

**Comment by basejump** [comment]
@snimavat  clear example of setting up events listeners in the refreshable beans, @EventListener won't work. I think it should be referenced and pointed to from docs on events. basically, doc what we are doing in the benchmarks with CitySpringEventsRefreshable and CityRefreshableBeanSubscriber (<- if that still relevant)

**Comment by basejump** [comment]
also, both `Defining refreshable beans using Spring dynamic language support.` and `Using external groovy beans as event listeners.` should be under the same section `External refreshable beans for Events`. try to shorten the titles a bit too so they don't wrap on the TOC to the right

**Comment by snimavat** [comment]
@basejump does the docs look good now ?
