### ISSUE TITLE
Create DaoDataTest trait and DaoHibernateSpec

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#53]
DaoDataTest can extend or implement from DataTest trait. so when we do this
```
    void setupSpec() {
        mockDomains TestClazzA, TestClazzB, TestClazzC
    }
```
it also wires up the daos.  should refactor how we do our dao setups so we can more easily reuse the same code to setup the unit test. 

https://testing.grails.org/latest/guide/index.html#unitTesting
can also look into getIncludePlugins

should also create a DaoHibernateSpec that extends HibernateSpec and does the same stuff needed to wire up the daos when we use the full HibernateSpec which works differently than using mockDomains with  DataTest.

**Comment by snimavat** [comment]
There's a catch here... when we want to have utility classes like this within plugin if we put them under test folder, they are not included in released jar. and if we put them under src/folder it needs whole grails testing framework to be included. There needs some gradle tricks

**Comment by basejump** [comment]
DaoDataTest is done and checked in. compileOnly will only include dependency for compile and will not distribbute it. no tricks needed.
