### ISSUE TITLE
Pager spec tests are virtually non-existant

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#55]
- add javadocs 
- document loadTotalFromDb where is it used, how to use it and whats it needed for if the paging list in grails has a count?
no test anywhere either that I can see for that either.

**Comment by alexeyzvegintcev** [comment]
@basejump the only mention for loadTotalFromDb Ive found:
https://github.com/9ci/rally/blob/9.9.x/src/main/groovy/nine/rally/FixPagedResultList.groovy#L9
It has the same code
