### ISSUE TITLE
domain nest order

### ISSUE THREAD

**Issue by ibmsoft** [yakworks/gorm-tools#561]
just want sort by mxes.ryes.c
`
class A {
 String a
 static hasMany = [mxes:B]
}
class B {
 String b
 static hasMany = [ryes:C]
}
class C {
 String c
}

`
in this examle ,how to set nest order
use follow throw exception
sort: { mxes.ryes.c: desc}

**Comment by basejump** [comment]
Hi, any way to reproduce what you are trying to in a fork? if you can create an example or test or what your trying to, ideally using some variation of rally-domain or the kitchenSink in gorm-test-domain, we can probably figure out how to make it work.
