### ISSUE TITLE
Long running query for lists in DefaultMangoQuery. 

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#605]
we are getting the following in logs. I dont think its actually a connection leak. its query that are running long. 
lets use the `Long stime = BenchmarkHelper.startTime()` before the list and after do something like we have in PaymentDetailArTranRepo but check if it exceeds a certain time (15 seconds maybe) log it. 

![image](https://user-images.githubusercontent.com/187726/208506445-e42667cf-7634-4c82-af74-418256cb81c1.png)

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/187726/208506166-6f7ba7f3-1599-45ff-a964-ac2d77d84c35.png">

see 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/187726/208505927-930d7728-9c43-4184-a1f2-f5171169c682.png">

**Comment by snimavat** [comment]
@basejump may be instead we can configure hibernate to log slow queries ? 
https://thorben-janssen.com/hibernate-slow-query-log/
https://vladmihalcea.com/hibernate-slow-query-log/

If we try to log queries at the method u mentioned above, or in MangoDetachedCriter.list - we have Criteria instance, which cant not be logged properly unless we have a custom toString() method on it.
