### ISSUE TITLE
set Events for Dao

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#63]
extend AbstractPersistenceEvent.

* Post and PreDaoPersistEvent
* Post and PreDaoRemoveEvent
* Post and PreDaoCreateEvent - will have the params accessible from bind. 
* Post and PreDaoUpdateEvent - will have the params accessible from bind.

These can be fired like they are in Gorm's EntityPersister class with publisher.publishEvent(event)

**Comment by basejump** [comment]
We need some docs and tests for this now. Also need to test the async @Subscriber router keys and document those.

**Comment by snimavat** [comment]
Duplicate https://github.com/yakworks/gorm-tools/issues/99
