### ISSUE TITLE
incorporate the Build Test Data

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#64]
incorporate and start using this helpful plugin to make sure it works with dao. extend where needed and help get it working with grails3.3
see https://github.com/longwa/build-test-data

**Comment by snimavat** [comment]
Related #65

**Comment by basejump** [comment]
waiting for plugin op to commit. see https://github.com/tkvw/gorm-build-test-data/issues/1

**Comment by snimavat** [comment]
Author has commited to master, all tests are good on master, we can make changes.

**Comment by snimavat** [comment]
Added the issue here https://github.com/longwa/build-test-data/issues/93
So we can give a PR against it.

**Comment by basejump** [comment]
Will be in the next release. I am have been corresponding with him and am a commiter on the project now
