### ISSUE TITLE
Binder can not bind associations with uuid as id fields

### ISSUE THREAD

**Issue by snimavat** [yakworks/gorm-tools#697]
We have some domains (PayTran/Wallet) that uses uuid as ids, but binder expects id to always be long... fails to bind those associations

eg PayTran.create(wallet:[id:uuid]) will fail to bind wallet to tran

@basejump

**Comment by basejump** [comment]
`PayTran.create(wallet:[id:uuid])` works fine. the problem is `PayTran.create(walletId: uuid])`
fixed in PR
