### ISSUE TITLE
Refactor Exceptions

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#74]
remove generic DomainException. All Exceptions should inherit from DataAccessException to stay within the Spring model. In Gorm see `ValidationException extends DataIntegrityViolationException`.

- we should possibly raise an issue and maybe issue a pull request so that Gorm keeps it instead of using grails.validation.ValidationException

- we still want to intercept and refire for ValidationExceptions

**Comment by alexeyzvegintcev** [comment]
created issue https://github.com/grails/grails-data-mapping/issues/1038  if they agreed with the idea then will start working on PR to remove grails ValidationException
