### ISSUE TITLE
Benchmarks: Add exceptions testing

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#76]
- want to see the impact of certain exception handling, such as validation.

**Comment by alexeyzvegintcev** [comment]
@basejump 
### Exception handling
-- single threaded without exception, just for comparison
5.872s for SimpleBatchInsert without gpars: databinding=true 

-- Exceptions thrown - EntityValidationException, catched - EntityValidationException
7.391s for ExceptionHandlingBenchmark without gpars: databinding=true 

-- Exceptions thrown - EntityValidationException, catched - DataAccessException
7.291s for ExceptionHandlingBenchmark without gpars: databinding=true 

-- Exceptions thrown - grails.validation.ValidationException, catched - grails.validation.ValidationException
7.405s for ExceptionHandlingBenchmark without gpars: databinding=true 

-- Exceptions thrown - EntityNotFoundException, catched - EntityNotFoundException
5.865s for ExceptionHandlingBenchmark without gpars: databinding=true
