### ISSUE TITLE
FastBinder refactor to a trait MapBinder

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#81]
Lets call it MapBinder and rename FastBinder to GormMapBinder
The default bean will be setup as `gormMapBinder(GormMapBinder)'
in the GormDao trait we can have 
```
@Autowired MapBinder mapBinder
```

Then if we have an explicitley definded dao we could abstract out special binding into its own bean and inject/override the mapBinder.
```
FooDao implements GormDao {
  @Autowired FooMapBinder mapBinder
....
```
 add something like this explanation (but better 😀) above to the docs to explain how it can be done.

inital work is started here https://github.com/yakworks/gorm-tools/tree/81-mapBinder

**Comment by basejump** [comment]
Docs need to be cleaned up

**Comment by basejump** [comment]
@snimavat docs need to be cleaned up. Keep code examples well formatted just like we would for source code.

**Comment by snimavat** [comment]
@basejump can this be closed ?

**Comment by basejump** [comment]
@snimavat `SomeService`  code format/indents are still off

**Comment by snimavat** [comment]
@basejump done
