### ISSUE TITLE
GormMapBinder enhancments

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#82]
finish #81 

- on update it needs to figure out what belongs to it and update fields if the map contains them. if its doesn't belong then it should be ignored and only look at the id to see if it needs to be changed.

- on a create it needs to create new associations if they belong and only load if they don't. the bindMethod can be used to know if we should be doing something special in each case. 

- a good example to create in tests is to simulate how we might create and update customers or arTrans in ar. In fact I think all of our tests should eb centered around using a customer/invoice type of simulation.

**Comment by snimavat** [comment]
@Josh i think we need to discuss the create/vs update and belongsTo stuff.
Updating only when belongsTo is different behavior than grails. Grails would bind associations regardless of belongsTo or cascading behavior.

Also, if we create new associations only during create and not during update, that may not work in all situations. Its possible that we want to create a new association during update. For example ArTranDispute. It could be needed that we want to create new ArTranDispute for an existing tran, not just when creating new ArTran. Or we may want to create new ArTranFlex and set new fields for existing ArTran during update.

**Comment by basejump** [comment]
we can see Gorm source for DirtyCheckingSupport.areAssociationsDirty for some ideas on how to get associations and ownership

**Comment by snimavat** [comment]
Also need to add support for collection types..
