### ISSUE TITLE
@GormRepository annotation for AST

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#88]
We want to be able to create Repository out side of the grails-app/repository dir. @Entity is used for domains and @Controller for controllers as an example. Should be able to do the same thing with @Dao.

**Comment by snimavat** [comment]
@basejump Actually [@Artefact("Dao")](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/artefact/Artefact.java) annotation is a general purpose annotation that will grab the related trait injectors every thing and apply it to an Artefact when its outside of grails application. This should be sufficient, why specifically we need @Dao

**Comment by basejump** [comment]
we will build on it for another task as well as use AST to add the transactional internals. We are going to build on top of it as well for a @RestApiDao annotation that will coordinate with the @RestApi annotation on the domain.

**Comment by snimavat** [comment]
Added annotation, similar to Controller.. can be updated as and when needed.
