### ISSUE TITLE
quickSearchFields for Mango should have defaults and be able to be set in config

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#89]
should default to [num,name,description] . can then check if fields exist and do the setup during plugin init.

**Comment by alexeyzvegintcev** [comment]
@basejump not sure about default values, as for me it would be more reasonable to set defaults only if they are in config, because `num` is very specific for example

**Comment by basejump** [comment]
thats what I mean. the config drives the feilds to look for. it can be anything
